server:
  port: 8080

spring:
  datasource:
#    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/one-moment
    username: user
    password: user
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none
#        show_sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml

bot:
  name: one_moment_dance_school_bot
  token: ${token}
  timeout: 30